// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGqUP661ECwjakBilw5eeFjJAfUlFsNoo',
    appId: '1:911203065805:web:2cd80dc03dac10c68d2e84',
    messagingSenderId: '911203065805',
    projectId: 'twitter2-4bbd9',
    authDomain: 'twitter2-4bbd9.firebaseapp.com',
    storageBucket: 'twitter2-4bbd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_vCZYs1Qd1BbKJJdiYZXjGHkD7eMAic',
    appId: '1:911203065805:android:2c5291688007c1f78d2e84',
    messagingSenderId: '911203065805',
    projectId: 'twitter2-4bbd9',
    storageBucket: 'twitter2-4bbd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-hK8IbYwpV5TcGxHcUc7nruxQNfNa6ak',
    appId: '1:911203065805:ios:23b2f87ce88fe26f8d2e84',
    messagingSenderId: '911203065805',
    projectId: 'twitter2-4bbd9',
    storageBucket: 'twitter2-4bbd9.appspot.com',
    iosClientId: '911203065805-l7cidsv413jhfrn1romuetj2gk10qp6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.twiiterClone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-hK8IbYwpV5TcGxHcUc7nruxQNfNa6ak',
    appId: '1:911203065805:ios:23b2f87ce88fe26f8d2e84',
    messagingSenderId: '911203065805',
    projectId: 'twitter2-4bbd9',
    storageBucket: 'twitter2-4bbd9.appspot.com',
    iosClientId: '911203065805-l7cidsv413jhfrn1romuetj2gk10qp6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.twiiterClone2',
  );
}
